development:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/development.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: slot_booking_production
  username: slot_booking
  password: <%= ENV['SLOT_BOOKING_DATABASE_PASSWORD'] %>
